# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[exceptions]
paths = [
    ".github/**",
]
[[annotations]]
path = [
    "VERSION",
    "**.md",
    "standalone-node/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
