# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gatekeeper-constraints
  namespace: kube-system
spec:
  chartContent:
  targetNamespace: gatekeeper-system
  valuesContent: |-
    policies:
      constraints:
        capabilities:
          enabled: false
        hostNetwork:
          enabled: false
        volumeTypes:
          enabled: false
        hostNamespace:
          enabled: false
        hostPorts:
          enabled: false
        privilegedContainer:
          enabled: false
        privilegedEscalation:
          enabled: false
        readOnlyFs:
          enabled: false
        sysctls:
          enabled: false
