# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chartContent:
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    installCRDs: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
    webhook:
      # Enables default network policies for webhooks.
      networkPolicy:
        enabled: true
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: 'kube-system'
    extraObjects:
      # yamllint disable rule:line-length
      # cert-manager
      - |
        apiVersion: crd.projectcalico.org/v1
        kind: NetworkPolicy
        metadata:
          name: allow-egress
          namespace: cert-manager
          annotations:
            helm.sh/hook: post-install
            helm.sh/hook-weight: "3"
        spec:
          order: 100
          selector: app.kubernetes.io/instance == '{{ .Release.Name }}' && app.kubernetes.io/component in  { 'webhook', 'controller', 'startupapicheck', 'cainjector' }
          types:
            - Egress
            - Ingress
          ingress:
            - action: Allow
              destination:
                services:
                  name: cert-manager-webhook
            - action: Pass
          egress:
            - action: Allow
              destination:
                services:
                  name: kubernetes
                  namespace: default
            - action: Allow
              destination:
                services:
                  name: rke2-coredns-rke2-coredns
                  namespace: kube-system
    # yamllint enable rule:line-length
    # cert-manager-config
      - |
        apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: edge-node-cluster-issuer
          annotations:
            helm.sh/hook: post-install
            helm.sh/hook-weight: "3"
        spec:
          ca:
            secretName: edgenode-root-secret
      - |
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        metadata:
          namespace: cert-manager
          name: cert-manager-allow-metrics-port-from-observability
        spec:
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
              app.kubernetes.io/instance: cert-manager
              app.kubernetes.io/name: cert-manager
          ingress:
            - ports:
                - port: 9402
              from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: observability
      - |
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: edgenode-selfsigned-ca
          annotations:
            helm.sh/hook: post-install
            helm.sh/hook-weight: "2"
        spec:
          isCA: true
          commonName: edgenode-selfsigned-ca
          secretName: edgenode-root-secret
          privateKey:
            algorithm: ECDSA
            size: 256
          issuerRef:
            name: selfsigned-issuer
            kind: Issuer
            group: cert-manager.io
      - |
        apiVersion: cert-manager.io/v1
        kind: Issuer
        metadata:
          name: selfsigned-issuer
          annotations:
            helm.sh/hook: post-install
            helm.sh/hook-weight: "1"
        spec:
          selfSigned: {}
