# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs
  namespace: kube-system
spec:
  chartContent:
  targetNamespace: openebs
  createNamespace: true
  valuesContent: |-
    engines:
      local:
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false

    apiserver:
      ## apiserver resource requests and limits
      ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi

    provisioner:
      ## provisioner resource requests and limits
      ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi

    # If you want to enable local pv as a dependency chart then set
    # `localprovisioner.enabled: false` and enable it as dependency chart.
    # If you are using custom configuration then update those configuration
    # under `localpv-provisioner` key.
    localprovisioner:
      ## localprovisioner resource requests and limits
      ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      hostpathClass:
        # Sets the openebs-hostpath StorageClass as the default StorageClass
        isDefaultClass: true

    # lvm local pv configuration goes here
    # ref - https://openebs.github.io/lvm-localpv
    lvm-localpv:
      # The crd portion is introduced in 24.08 in order
      # to allow for upgrade of OpenEBS from
      # 3.x to 4.1.x
      # By default creation of CRD will be disabled in
      # both upgrade and fresh install scenario in the
      # opesource openEBS chart - in our own chart the
      # CRDs are copied/edited and deployed
      # of a CRD alrady present on the cluster rather
      # than the flag. based on detection
      crds:
        lvmLocalPv:
          enabled: false
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
      lvmController:
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
      lvmNode:
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
