# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: telegraf
  namespace: kube-system
spec:
  chartContent:
  targetNamespace: observability
  valuesContent: |-
    volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
      - name: certs
        secret:
          secretName: telegraf-tls
    mountPoints:
      - name: telegraf-config
        mountPath: /etc/telegraf/
        # subPath: base-ext-telegraf.conf
        readOnly: true
      - name: certs
        mountPath: /opt/telegraf/certs

    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 128Mi
        cpu: 100m

    containerPorts:
      - name: metrics
        containerPort: 9105
        protocol: TCP

    image:
      pullPolicy: IfNotPresent
    args:
      - "--config=/etc/telegraf/base-ext-telegraf.conf"
    serviceAccount:
      create: false
    service:
      enabled: false
