---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# shellcheck disable=all

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

# Cloud-config file to start the k3s cluster.
runcmd:
  - |
    source /etc/environment

    iptables -A INPUT -p tcp -j ACCEPT

    # Start the K8* scripts only once
    if [ ! -f "/var/lib/rancher/k3s_status" ]; then
        mkdir -p /tmp/k3s-artifacts/
        tar -xf /opt/sen-k3s-package.tar.gz -C /tmp/k3s-artifacts/

        cd /tmp/k3s-artifacts/

        chmod +x sen-k3s-installer.sh

        bash sen-k3s-installer.sh
    else
       echo "k3s is already installed and running. Skipping installation."
       cd /etc/cloud/
       chmod +x k3s-setup-post-reboot.sh
       bash k3s-setup-post-reboot.sh
    fi
