---

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

# Cloud-config file to start the rke2 cluster.
runcmd:
  - |
    source /etc/environment

    iptables -A INPUT -p tcp -j ACCEPT

    # Start the K8* scripts
    mkdir -p /tmp/rke2-artifacts/
    tar -xf /opt/sen-rke2-package.tar.gz -C /tmp/rke2-artifacts/

    cd /tmp/rke2-artifacts/

    chmod +x sen-rke2-installer.sh

    bash sen-rke2-installer.sh
