---

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

# Cloud-config file to start the rke2 cluster.
runcmd:
  - |
    source /etc/environment

    iptables -A INPUT -p tcp -j ACCEPT

    # Start the K8* scripts
    mkdir -p /tmp/rke2-artifacts/
    tar -xf /opt/sen-rke2-package.tar.gz -C /tmp/rke2-artifacts/

    cd /tmp/rke2-artifacts/

    chmod +x sen-rke2-installer.sh

    bash sen-rke2-installer.sh

    # Activate the USB device 
    efibootmgr | grep '^Boot[0-9A-Fa-f]\{4\}' | while read -r line; do
      BOOTNUM=$(echo "$line" | cut -c5-8)
      HAS_ASTERISK=$(echo "$line" | grep -o '\*')

      if [ -z "$HAS_ASTERISK" ]; then
        echo "Enabling disabled boot entry: $BOOTNUM"
        efibootmgr -b "$BOOTNUM" -a
      fi
    done

