---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

# Cloud-config file to start the k3s cluster.
runcmd:
  - |
    source /etc/environment

    iptables -A INPUT -p tcp -j ACCEPT

    # Start the K8* scripts
    mkdir -p /tmp/k3s-artifacts/
    tar -xf /opt/sen-k3s-package.tar.gz -C /tmp/k3s-artifacts/

    cd /tmp/k3s-artifacts/

    chmod +x sen-k3s-installer.sh

    bash sen-k3s-installer.sh

    # Activate the USB device
    efibootmgr | grep '^Boot[0-9A-Fa-f]\{4\}' | while read -r line; do
      BOOTNUM=$(echo "$line" | cut -c5-8)
      HAS_ASTERISK=$(echo "$line" | grep -o '\*')

      if [ -z "$HAS_ASTERISK" ]; then
        echo "Enabling disabled boot entry: $BOOTNUM"
        efibootmgr -b "$BOOTNUM" -a
      fi
    done
