---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# shellcheck disable=all

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

# Cloud-config file to start the rke2 cluster.
runcmd:
  - |
    source /etc/environment

    iptables -A INPUT -p tcp -j ACCEPT

    # Start the K8* scripts only once
    if [ ! -f "/var/lib/rancher/rke2_status" ]; then
        mkdir -p /tmp/rke2-artifacts/
        tar -xf /opt/sen-rke2-package.tar.gz -C /tmp/rke2-artifacts/

        cd /tmp/rke2-artifacts/

        chmod +x sen-rke2-installer.sh

        bash sen-rke2-installer.sh
    else
       echo "RKE2 is already installed and running. Skipping installation."
       cd /etc/cloud/
       chmod +x rke2-setup-post-reboot.sh
       bash rke2-setup-post-reboot.sh
    fi
