---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Labeler

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write      # needed so the action can apply labels to PRs
  issues: write             # needed so the action can apply labels to Issues

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    # Only run for PRs from the main repository (skip forks like Dependabot)
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.actor != 'dependabot[bot]'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d  # v6.2.0
        with:
          repo-token: ${{ secrets.SYS_EMF_GH_TOKEN }}
