   name: PublishToAWS
   on:
    workflow_dispatch:
   env:
      # proxy-dmz mangles DNS resolution, resulting in certificate verification failure
      http_proxy: http://proxy-chain.intel.com:912
      https_proxy: http://proxy-chain.intel.com:912
      no_proxy: localhost,127.0.0.1/8,ch.intel.com,ka.intel.com,devtools.intel.com

   jobs:
      build:
        uses: intel-innersource/applications.services.esh.intel-edge-services-document/.github/workflows/publishtoaws.yml@release-1.0
        permissions:
         contents: read
         issues: read
         pull-requests: read
        secrets:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}